eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

server:
  port: 8083

management:
  security.enabled: false
  context-path: /