endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

server:
  port: 8080

zuul:
  routes:
    dummy:
      path: /dummy/**
      serviceId: dummy-service

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true