server:
  port: 8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    instance:
      preferIpAddress: true

management:
  security.enabled: false
  context-path: /

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springcloudy/config.git
  rabbitmq:
    address: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:127.0.0.1}:${RABBITMQ_PORT:5672}}